// WARNING: This file has automatically been generated on Mon, 21 Oct 2024 23:38:34 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int CNDEV_TRAVERSE_CALLBACK_1ddf08dd(cndevTopologyNode_t* current, void* userdata) {
	return tRAVERSE_CALLBACK1DDF08DD(current, userdata);
}

