// WARNING: This file has automatically been generated on Mon, 21 Oct 2024 23:38:34 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "cndev.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// CNDEV_TRAVERSE_CALLBACK_1ddf08dd is a proxy for callback CNDEV_TRAVERSE_CALLBACK.
int CNDEV_TRAVERSE_CALLBACK_1ddf08dd(cndevTopologyNode_t* current, void* userdata);

