// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 21 Oct 2024 09:12:13 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package lib

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#cgo darwin LDFLAGS: -Wl,-undefined,dynamic_lookup
#include "cndev.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// VERSION_1 as defined in lib/cndev.h:17
	VERSION_1 = 1
	// VERSION_2 as defined in lib/cndev.h:18
	VERSION_2 = 2
	// VERSION_3 as defined in lib/cndev.h:19
	VERSION_3 = 3
	// VERSION_4 as defined in lib/cndev.h:20
	VERSION_4 = 4
	// VERSION_5 as defined in lib/cndev.h:21
	VERSION_5 = 5
	// UUID_SIZE as defined in lib/cndev.h:135
	UUID_SIZE = 37
	// IP_ADDRESS_LEN as defined in lib/cndev.h:139
	IP_ADDRESS_LEN = 40
)

// Ret_t as declared in lib/cndev.h:56
type Ret_t int32

// Ret_t enumeration from lib/cndev.h:56
const (
	SUCCESS                       Ret_t = iota
	ERROR_NO_DRIVER               Ret_t = 1
	ERROR_LOW_DRIVER_VERSION      Ret_t = 2
	ERROR_UNSUPPORTED_API_VERSION Ret_t = 3
	ERROR_UNINITIALIZED           Ret_t = 4
	ERROR_INVALID_ARGUMENT        Ret_t = 5
	ERROR_INVALID_DEVICE_ID       Ret_t = 6
	ERROR_UNKNOWN                 Ret_t = 7
	ERROR_MALLOC                  Ret_t = 8
	ERROR_INSUFFICIENT_SPACE      Ret_t = 9
	ERROR_NOT_SUPPORTED           Ret_t = 10
	ERROR_INVALID_LINK            Ret_t = 11
	ERROR_NO_DEVICES              Ret_t = 12
	ERROR_NO_PERMISSION           Ret_t = 13
)

// NameEnum_t as declared in lib/cndev.h:69
type NameEnum_t int32

// NameEnum_t enumeration from lib/cndev.h:69
const ()

// TopologyRelationshipEnum_t as declared in lib/cndev.h:79
type TopologyRelationshipEnum_t int32

// TopologyRelationshipEnum_t enumeration from lib/cndev.h:79
const ()

// MLULinkSpeedEnum_t as declared in lib/cndev.h:84
type MLULinkSpeedEnum_t int32

// MLULinkSpeedEnum_t enumeration from lib/cndev.h:84
const ()

// MLULinkCounterEnum_t as declared in lib/cndev.h:98
type MLULinkCounterEnum_t int32

// MLULinkCounterEnum_t enumeration from lib/cndev.h:98
const ()

// EnableStatusEnum_t as declared in lib/cndev.h:103
type EnableStatusEnum_t int32

// EnableStatusEnum_t enumeration from lib/cndev.h:103
const (
	FEATURE_DISABLED EnableStatusEnum_t = iota
	FEATURE_ENABLED  EnableStatusEnum_t = 1
)

// RetirePageCauseEnum_t as declared in lib/cndev.h:577
type RetirePageCauseEnum_t int32

// RetirePageCauseEnum_t enumeration from lib/cndev.h:577
const (
	PAGE_RETIREMENT_CAUSE_MULTIPLE_SINGLE_BIT_ECC_ERRORS RetirePageCauseEnum_t = iota
	PAGE_RETIREMENT_CAUSE_DOUBLE_BIT_ECC_ERROR           RetirePageCauseEnum_t = 1
)

// PortModeEnum_t as declared in lib/cndev.h:615
type PortModeEnum_t int32

// PortModeEnum_t enumeration from lib/cndev.h:615
const ()

// RoceFieldEnum_t as declared in lib/cndev.h:644
type RoceFieldEnum_t int32

// RoceFieldEnum_t enumeration from lib/cndev.h:644
const ()

const ()

const ()

const ()

const ()
