// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 21 Oct 2024 09:12:13 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package alac provides Go bindings for ALAC decoder (C version by David Hammerton).
*/
package lib
