---
kind: pipeline
name: deviceplugin
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
#  - name: 构建镜像
#    image: swr.cn-south-1.myhuaweicloud.com/krakenplug/docker:20.10.6-make
#    volumes:
#      - name: docker
#        path: /var/run/
#    commands:
#      - make deviceplugin_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/krakenplug/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make deviceplugin_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: deviceexporter
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
#  - name: 构建镜像
#    image: swr.cn-south-1.myhuaweicloud.com/krakenplug/docker:20.10.6-make
#    volumes:
#      - name: docker
#        path: /var/run/
#    commands:
#      - make deviceexporter_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/krakenplug/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make deviceexporter_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---

kind: pipeline
name: devicediscovery
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: docker
    host:
      path: /var/run/
steps:
  #  - name: 构建镜像
  #    image: swr.cn-south-1.myhuaweicloud.com/krakenplug/docker:20.10.6-make
  #    volumes:
  #      - name: docker
  #        path: /var/run/
  #    commands:
  #      - make devicediscovery_image tag=${DRONE_TAG}

  - name: 镜像推送
    image: swr.cn-south-1.myhuaweicloud.com/krakenplug/docker:20.10.6-make
    volumes:
      - name: docker
        path: /var/run/
    environment:
      DOCKER_HUB_HOST:
        from_secret: docker_hub_host
      DOCKER_HUB_USERNAME:
        from_secret: docker_hub_userame
      DOCKER_HUB_PASSWD:
        from_secret: docker_hub_passwd
      DOCKER_HUB_PROJECT:
        from_secret: docker_hub_project
    commands:
      - make devicediscovery_image_push need_latest=FALSE tag=${DRONE_TAG} docker_hub_project=$DOCKER_HUB_PROJECT docker_hub_host=$DOCKER_HUB_HOST docker_hub_userame=$DOCKER_HUB_USERNAME docker_hub_passwd=$DOCKER_HUB_PASSWD

---
kind: pipeline
name: charts
type: kubernetes
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - tag
volumes:
  - name: dockeretc
    host:
      path: /etc/docker
steps:
  - name: Chart构建
    image: swr.cn-south-1.myhuaweicloud.com/openioctopus/helm:3.5.4-make
    volumes:
      - name: dockeretc
        path: /etc/docker
    environment:
      CHARTS_GIT_CLONE:
        from_secret: charts_git_clone
      CHARTS_GIT_RAW:
        from_secret: charts_git_raw
      CHARTS_GIT_USER_NAME:
        from_secret: charts_git_user_name
      CHARTS_GIT_USER_EMAIL:
        from_secret: charts_git_user_email
    commands:
      - make charts drone_repo=${DRONE_REPO} tag=${DRONE_TAG} charts_git_clone=$CHARTS_GIT_CLONE charts_git_raw=$CHARTS_GIT_RAW charts_git_user_name=$CHARTS_GIT_USER_NAME charts_git_user_email=$CHARTS_GIT_USER_EMAIL
