apiVersion: v1
kind: Namespace
metadata:
  name: krakenplug
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: krakenplug-deviceplugin
  namespace: krakenplug
  labels:
    app.kubernetes.io/name: krakenplug-deviceplugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: krakenplug-deviceplugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: krakenplug-deviceplugin
    spec:
      containers:
        - name: krakenplug-deviceplugin
          securityContext:
            privileged: true
          image: "deviceplugin:v1.0"
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys
              readOnly: true
              mountPath: /sys
            - name: usr
              readOnly: true
              mountPath: /host/usr
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: usr
          hostPath:
            path: /usr
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: krakenplug-deviceexporter
  namespace: krakenplug
  labels:
    app.kubernetes.io/name: krakenplug-deviceexporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: krakenplug-deviceexporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: krakenplug-deviceexporter
    spec:
      containers:
        - name: krakenplug-deviceexporter
          securityContext:
            privileged: true
          image: "deviceexporter:v1.0"
          env:
            - name: KRAKENPLUG_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: pod-resources
              readOnly: true
              mountPath: /var/lib/kubelet/pod-resources
            - name: sys
              readOnly: true
              mountPath: /sys
            - name: usr
              readOnly: true
              mountPath: /host/usr
      volumes:
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
        - name: sys
          hostPath:
            path: /sys
        - name: usr
          hostPath:
            path: /usr
---
apiVersion: v1
kind: Service
metadata:
  name: krakenplug-deviceexporter
  namespace: krakenplug
  labels:
    app.kubernetes.io/name: krakenplug-deviceexporter
  annotations:
    prometheus.io/port: "9400"
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9400
      targetPort: 9400
  selector:
    app.kubernetes.io/name: krakenplug-deviceexporter