apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devicedescovery.fullname" . }}
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "devicedescovery.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "devicedescovery.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "devicedescovery.fullname" . }}
  labels:
    {{- include "devicedescovery.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "devicedescovery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devicedescovery.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
          #image: "devicedescovery:v1.0"
          image: "{{ .Values.global.image.repository.address }}/{{ .Values.devicedescovery.image.name }}:{{ default .Chart.AppVersion .Values.devicedescovery.image.tag }}"
          env:
            - name: KRAKENPLUG_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: pod-resources
              readOnly: true
              mountPath: /var/lib/kubelet/pod-resources
            - name: sys
              readOnly: true
              mountPath: /sys
            - name: usr
              readOnly: true
              mountPath: /host/usr
      volumes:
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
        - name: sys
          hostPath:
            path: /sys
        - name: usr
          hostPath:
            path: /usr