apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "deviceplugin.fullname" . }}
  labels:
    {{- include "deviceplugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "deviceplugin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deviceplugin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            #由于有些晟腾设备无法多个容器挂载同一个设备，这里使用privileged模式解决
            privileged: true
          #image: "deviceplugin:v1.0"
          image: "{{ .Values.image.repository.address }}/{{ .Values.deviceplugin.image.name }}:{{ default .Chart.AppVersion .Values.deviceplugin.image.tag }}"
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
